# Generated by Django 2.0.6 on 2018-08-18 23:56

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OcrTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('_deleted', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='image_processed')),
                ('predictions', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), size=None)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('is_prediction', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
                'ordering': ['-created_at'],
            },
        ),
    ]
