# Generated by Django 2.0.6 on 2018-08-19 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_net', '0003_ocrtrack_predictions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocrtrack',
            old_name='is_prediction',
            new_name='success_prediction',
        ),
    ]
